# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Responsibility', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Image', models.ImageField(default='Team/default.jpg', upload_to='Team')),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Strength', models.CharField(max_length=1000)),
                ('Weakness', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='FeasibilityScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FilterName', models.CharField(default='', max_length=100)),
                ('Loction', models.CharField(default='', max_length=100)),
                ('BSector', models.CharField(default='', max_length=100)),
                ('StartupStage', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualAddOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusinessType', models.CharField(blank=True, max_length=50)),
                ('StartupsFunded', models.CharField(blank=True, max_length=5)),
                ('URL', models.CharField(blank=True, max_length=50)),
                ('Pic', models.ImageField(blank=True, upload_to='profile')),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Username', models.CharField(default='', max_length=100)),
                ('Contact', models.CharField(default='123456', max_length=15)),
                ('City', models.CharField(default='Pune', max_length=20)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationAddOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrganizationType', models.CharField(max_length=50)),
                ('URL', models.CharField(max_length=50)),
                ('YearFounded', models.CharField(max_length=4)),
                ('Size', models.CharField(max_length=6)),
                ('BusinessType', models.CharField(max_length=50)),
                ('Specialites', models.CharField(max_length=500)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.Investor')),
            ],
        ),
        migrations.CreateModel(
            name='PortFolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvRequest', models.CharField(default='PENDING', max_length=100)),
                ('StrRequest', models.CharField(default='PENDING', max_length=100)),
                ('InvPortfolio', models.BooleanField(default=False)),
                ('StrPortfolio', models.BooleanField(default=False)),
                ('InvestorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.Investor')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Problem', models.CharField(max_length=200)),
                ('Need', models.CharField(max_length=200)),
                ('ExistingSolution', models.CharField(max_length=200)),
                ('How', models.CharField(max_length=200)),
                ('AddressedNeeds', models.CharField(max_length=200)),
                ('Better', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('ProductImage', models.ImageField(default='Team/default.jpg', upload_to='Team')),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Username', models.CharField(default='', max_length=100)),
                ('Contact', models.CharField(default='123456', max_length=15)),
                ('City', models.CharField(default='Pune', max_length=20)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StartupAddOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=50)),
                ('Stage', models.CharField(max_length=100)),
                ('Tagline', models.CharField(max_length=100)),
                ('Website', models.CharField(max_length=100)),
                ('BusinessSector', models.CharField(max_length=100)),
                ('UVP', models.CharField(max_length=1000)),
                ('CompetitiveAdvantage', models.CharField(max_length=1000)),
                ('TargetCustomers', models.CharField(max_length=500)),
                ('Threats', models.CharField(max_length=200)),
                ('Summary', models.CharField(max_length=1000)),
                ('LOGO', models.ImageField(blank=True, upload_to='Team')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.Startup')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.Startup'),
        ),
        migrations.AddField(
            model_name='problemsolution',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.Startup'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='StartupId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.Startup'),
        ),
        migrations.AddField(
            model_name='individualaddon',
            name='Username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.Investor'),
        ),
        migrations.AddField(
            model_name='filters',
            name='InvestorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.Investor'),
        ),
        migrations.AddField(
            model_name='feasibilityscore',
            name='StartupId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.Startup'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.Startup'),
        ),
        migrations.AddField(
            model_name='associate',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.Startup'),
        ),
    ]
