# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualAddOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusinessType', models.CharField(max_length=50)),
                ('StartupsFunded', models.CharField(max_length=5)),
                ('URL', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Username', models.CharField(default='', max_length=100)),
                ('Contact', models.CharField(default='123456', max_length=15)),
                ('City', models.CharField(default='Pune', max_length=20)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationAddOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrganizationType', models.CharField(max_length=50)),
                ('URL', models.CharField(max_length=50)),
                ('YearFounded', models.CharField(max_length=4)),
                ('Size', models.CharField(max_length=6)),
                ('BusinessType', models.CharField(max_length=50)),
                ('Specialites', models.CharField(max_length=500)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.Investor')),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Username', models.CharField(default='', max_length=100)),
                ('Contact', models.CharField(default='123456', max_length=15)),
                ('City', models.CharField(default='Pune', max_length=20)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='individualaddon',
            name='Username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.Investor'),
        ),
    ]
