# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('BusinessSector', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Stage', models.CharField(max_length=50)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.Investor')),
            ],
        ),
    ]
