# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='City',
            field=models.CharField(default='Pune', max_length=20),
        ),
        migrations.AddField(
            model_name='investor',
            name='Contact',
            field=models.CharField(default='123456', max_length=15),
        ),
        migrations.AddField(
            model_name='investor',
            name='Username',
            field=models.CharField(default='NULL', max_length=100),
            preserve_default=False,
        ),
    ]
