# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('What', models.CharField(max_length=200)),
                ('Need', models.CharField(max_length=200)),
                ('ExistSolution', models.CharField(max_length=200)),
                ('How', models.CharField(max_length=200)),
                ('Satisfies', models.CharField(max_length=200)),
                ('Better', models.CharField(max_length=200)),
            ],
        ),
    ]
