# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_problemsolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupAddOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=50)),
                ('Stage', models.CharField(max_length=100)),
                ('Tagline', models.CharField(max_length=100)),
                ('Website', models.CharField(max_length=100)),
                ('BusinessSector', models.CharField(max_length=100)),
                ('UVP', models.CharField(max_length=200)),
                ('CompetitiveAdvantage', models.CharField(max_length=200)),
                ('TargetCustomers', models.CharField(max_length=200)),
                ('Threats', models.CharField(max_length=200)),
                ('Summary', models.CharField(max_length=1000)),
                ('Problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.ProblemSolution')),
            ],
        ),
    ]
