# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-21 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_auto_20180321_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualAddOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusinessType', models.CharField(max_length=50)),
                ('StartupsFunded', models.CharField(max_length=5)),
                ('URL', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationAddOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrganizationType', models.CharField(max_length=50)),
                ('URL', models.CharField(max_length=50)),
                ('YearFounded', models.CharField(max_length=4)),
                ('Size', models.CharField(max_length=6)),
                ('BusinessType', models.CharField(max_length=50)),
                ('Specialites', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='investor',
            name='Username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
