# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0003_auto_20180331_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='BusinessSector',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='filter',
            name='Location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='filter',
            name='Stage',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
