# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0003_startupaddon'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeasibilityScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.IntegerField(default=0)),
                ('StartupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.Startup')),
            ],
        ),
    ]
