# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0004_auto_20180331_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='BusinessSector',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='Location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='Stage',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
