# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0004_feasibilityscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feasibilityscore',
            name='Score',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
