# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0005_auto_20180331_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActiveFilter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.Filter')),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.Investor')),
            ],
        ),
    ]
